export const BUILTIN_WORKER_KINDS = [
  'autofix',
  'heartbeat-requeue',
  'workflow-resume',
  'pr-status',
  'infra-repair',
  'disk-headroom',
  'claude-oauth-refresh',
  'reaper',
  'db-reaper',
  'autoapprove',
  'pr-admin-bypass-land',
  'pr-orphan-repair',
  'pr-duplicate-close',
  'pr-jailbreak-land',
  'pr-auto-label',
  'e2e-autofix',
  'worker-session-mine',
  'session-token-push',
  'slack-bug-scan',
  'idle-task-cleanup',
  'cross-repo-research',
  'catstack-deploy',
  'self-deploy',
  'admin-bypass-e2e-babysit',
  'mergify-queue-research',
  'spend-circuit-breaker',
  'workflow-cleanup',
  'agent-login-watch',
] as const;

export type BuiltinWorkerKind = (typeof BUILTIN_WORKER_KINDS)[number];
