/**
 * SessionDriver — post-execution session processing, separate from ExecutionAgent.
 *
 * Agents say what to run. Drivers handle what happens to the output after exit.
 * Co-registered alongside the agent via AgentRegistry.registerExecution().
 */

import type { AgentMessage } from './codex-session.js';
import type { CostConfidence } from '@invoker/contracts';

export interface RemoteTarget {
  host: string;
  user: string;
  sshKeyPath: string;
  port?: number;
}

export type AgentSessionState = 'running' | 'finished' | 'error';

export interface AgentSessionInspection {
  state: AgentSessionState;
  reason?: string;
}

/**
 * A single usage event extracted from a raw session transcript.
 *
 * Contains only session-local data. Attribution (workflow/task/attempt)
 * is attached downstream when the caller has that context.
 */
export interface SessionUsageEvent {
  /** Stable event identifier (derived from line position or provider event ID). */
  readonly eventId: string;
  /** ISO 8601 timestamp from the event, or empty string if absent. */
  readonly timestamp: string;
  /** Model identifier as reported by the provider, or empty string if absent. */
  readonly model: string;
  /** Tokens sent to the model. */
  readonly inputTokens: number;
  /** Tokens generated by the model. */
  readonly outputTokens: number;
  /** Input tokens served from cache (subset of inputTokens). */
  readonly cachedTokens: number;
  /** inputTokens + outputTokens. */
  readonly totalTokens: number;
  /** How confident we are that these numbers are accurate. */
  readonly confidence: CostConfidence;
}

export interface SessionDriver {
  /** Post-exit: store raw stdout and return human-readable text for callers. */
  processOutput(sessionId: string, rawStdout: string): string;
  /** Load stored session content by ID for viewing. */
  loadSession(sessionId: string): string | null;
  /** Parse stored session content into displayable messages. */
  parseSession(raw: string): AgentMessage[];
  /** Inspect a stored session and infer a small lifecycle state. */
  inspectSession(raw: string): AgentSessionInspection;
  /** Extract the real backend session/thread ID from raw stdout (e.g. codex thread ID for resume). */
  extractSessionId?(rawStdout: string): string | undefined;
  /** Fetch session from a remote SSH host. Returns raw content or null. */
  fetchRemoteSession?(sessionId: string, target: RemoteTarget): Promise<string | null>;
  /** Extract normalized usage events from raw session content. */
  extractUsage?(raw: string): SessionUsageEvent[];
}
