/**
 * Normalized Cost/Usage Types
 *
 * Provider-agnostic contract for cost and usage data.
 * All providers (Claude, GPT, Codex, etc.) map their raw events
 * into this shape so consumers never branch on provider identity.
 */

// ── Identity ────────────────────────────────────────────────

/** Who produced this cost event and where it came from. */
export interface CostEventIdentity {
  /** Unique identifier for this cost event. */
  readonly eventId: string;
  /** Session that produced this event (e.g. Claude session ID, Codex run ID). */
  readonly agentSessionId: string;
  /** Human-readable agent name (e.g. 'claude', 'codex', 'gpt-4o'). */
  readonly agentName: string;
  /** Originating provider (e.g. 'anthropic', 'openai'). */
  readonly source: string;
}

// ── Attribution ─────────────────────────────────────────────

/** Links a cost event to the workflow/task/attempt that incurred it. */
export interface CostEventAttribution {
  /** Workflow that owns this cost. */
  readonly workflowId: string;
  /** Task within the workflow. */
  readonly taskId: string;
  /** Specific execution attempt. */
  readonly attemptId: string;
  /** Executor type that ran the attempt (e.g. 'worktree', 'docker'). */
  readonly runnerKind: string;
}

// ── Usage ───────────────────────────────────────────────────

/** Token counts normalized across providers. */
export interface CostEventUsage {
  /** Tokens sent to the model. */
  readonly inputTokens: number;
  /** Tokens generated by the model. */
  readonly outputTokens: number;
  /** Input tokens served from cache (subset of inputTokens). */
  readonly cachedTokens: number;
  /** inputTokens + outputTokens. */
  readonly totalTokens: number;
}

// ── Pricing / Meta ──────────────────────────────────────────

/** How confident are we in the cost estimate? */
export type CostConfidence = 'exact' | 'estimated' | 'unknown';

/** Pricing metadata and cost estimate for a single event. */
export interface CostEventPricing {
  /** Model identifier as reported by the provider. */
  readonly model: string;
  /** Version of the pricing table used for the estimate. */
  readonly pricingVersion: string;
  /** Estimated cost in USD. */
  readonly estimatedCostUsd: number;
  /** How confident we are in the estimate. */
  readonly confidence: CostConfidence;
}

// ── Composed Event ──────────────────────────────────────────

/** A single normalized cost event combining all facets. */
export interface NormalizedCostEvent {
  readonly identity: CostEventIdentity;
  readonly attribution: CostEventAttribution;
  readonly usage: CostEventUsage;
  readonly pricing: CostEventPricing;
  /** ISO 8601 timestamp when the event was recorded. */
  readonly timestamp: string;
}

// ── Rollup Totals ───────────────────────────────────────────

/** Aggregated cost/usage across multiple events. */
export interface CostRollup {
  /** Sum of inputTokens across events. */
  readonly inputTokens: number;
  /** Sum of outputTokens across events. */
  readonly outputTokens: number;
  /** Sum of cachedTokens across events. */
  readonly cachedTokens: number;
  /** Sum of totalTokens across events. */
  readonly totalTokens: number;
  /** Sum of estimatedCostUsd across events. */
  readonly totalCostUsd: number;
  /** Number of events with confidence === 'unknown'. */
  readonly unknownConfidenceCount: number;
  /** Number of events where usage data was missing or zero. */
  readonly missingUsageCount: number;
  /** Number of events rolled up. */
  readonly eventCount: number;
}

// ── Factory / Helper ────────────────────────────────────────

/** Create an empty rollup for accumulation. */
export function emptyCostRollup(): CostRollup {
  return {
    inputTokens: 0,
    outputTokens: 0,
    cachedTokens: 0,
    totalTokens: 0,
    totalCostUsd: 0,
    unknownConfidenceCount: 0,
    missingUsageCount: 0,
    eventCount: 0,
  };
}

/** Accumulate a single event into a rollup. Returns a new rollup (immutable). */
export function accumulateCostEvent(rollup: CostRollup, event: NormalizedCostEvent): CostRollup {
  const usageMissing = event.usage.totalTokens === 0;
  return {
    inputTokens: rollup.inputTokens + event.usage.inputTokens,
    outputTokens: rollup.outputTokens + event.usage.outputTokens,
    cachedTokens: rollup.cachedTokens + event.usage.cachedTokens,
    totalTokens: rollup.totalTokens + event.usage.totalTokens,
    totalCostUsd: rollup.totalCostUsd + event.pricing.estimatedCostUsd,
    unknownConfidenceCount: rollup.unknownConfidenceCount + (event.pricing.confidence === 'unknown' ? 1 : 0),
    missingUsageCount: rollup.missingUsageCount + (usageMissing ? 1 : 0),
    eventCount: rollup.eventCount + 1,
  };
}

/** Roll up an array of events into a single CostRollup. */
export function rollUpCostEvents(events: readonly NormalizedCostEvent[]): CostRollup {
  return events.reduce(accumulateCostEvent, emptyCostRollup());
}
