#!/usr/bin/env bash
#
# Deterministic repro for the redundant post-bootstrap startup snapshot
# request (`useTasks_snapshot_replace` fired with `forceRefresh=false`
# after `preload_bootstrap_sync` has already delivered the full state).
#
# The fixture:
#   1. Seeds an isolated INVOKER_DB_DIR with several workflows / tasks by
#      launching the built Electron app once and calling `loadPlan`.
#   2. Re-launches the app against the same DB. The preload bootstrap
#      delivers a non-empty snapshot, then `useTasks.fetchAll()` runs and
#      currently re-issues a full `getTasks()` snapshot replace.
#   3. Collects `ui-perf` activity_log rows via the IPC bridge and looks
#      for a non-forced `useTasks_snapshot_replace` recorded AFTER
#      `preload_bootstrap_sync` -- that is the redundant request the
#      perf data shows costs ~65-164ms and ~377KB after the graph is
#      already visible.
#
# Flags:
#   --expect-issue   Exit 0 on the current (buggy) baseline when the
#                    redundant non-forced snapshot is observed (the bug
#                    is reproducible). Exit 1 otherwise.
#   (no flag)        Exit 0 only when the redundant non-forced snapshot
#                    is absent -- used to verify the optimisation.
#
#   --workflows N    Number of workflows to seed (default: 6).
#   --tasks N        Tasks per workflow (default: 4).
#   --keep-tmp       Skip cleaning up the isolated tmpdir (for debugging).
#
# The script prints:
#   * bootstrap task/workflow counts and jsonSizeBytes
#   * useTasks_snapshot_replace.requestDurationMs
#   * useTasks_snapshot_replace.replaceDurationMs
#   * graph visible timing and node/edge counts
#   * whether the snapshot was forced

set -euo pipefail

EXPECT_ISSUE=0
WORKFLOW_COUNT=6
TASKS_PER_WORKFLOW=4
KEEP_TMP=0

usage() {
  sed -n '2,/^set -euo pipefail$/p' "$0" | sed -e 's/^# \{0,1\}//' -e '/^set -euo/d'
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --expect-issue)   EXPECT_ISSUE=1; shift ;;
    --workflows)      WORKFLOW_COUNT="$2"; shift 2 ;;
    --workflows=*)    WORKFLOW_COUNT="${1#--workflows=}"; shift ;;
    --tasks)          TASKS_PER_WORKFLOW="$2"; shift 2 ;;
    --tasks=*)        TASKS_PER_WORKFLOW="${1#--tasks=}"; shift ;;
    --keep-tmp)       KEEP_TMP=1; shift ;;
    -h|--help)        usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/invoker-startup-snapshot-repro.XXXXXX")"
DB_DIR="$TMP_DIR/db"
BARE_REPO="$TMP_DIR/remote.git"
CONFIG_PATH="$TMP_DIR/e2e-config.json"
DRIVER_TMP="$ROOT_DIR/packages/app/.repro-startup-snapshot-driver.tmp.mjs"
OUT_JSON="$TMP_DIR/result.json"

cleanup() {
  rm -f "$DRIVER_TMP" 2>/dev/null || true
  if [[ "$KEEP_TMP" -ne 1 ]]; then
    rm -rf "$TMP_DIR"
  else
    echo "repro: keeping tmpdir at $TMP_DIR" >&2
  fi
}
trap cleanup EXIT

mkdir -p "$DB_DIR"
cat >"$CONFIG_PATH" <<'JSON'
{"autoFixRetries":0,"disableAutoRunOnStartup":true}
JSON

git init --quiet --bare "$BARE_REPO"
(
  TMP_WORK="$TMP_DIR/seed-clone"
  git clone --quiet "$BARE_REPO" "$TMP_WORK"
  cd "$TMP_WORK"
  git -c user.email=repro@invoker.dev -c user.name=Repro commit --allow-empty -q -m init
  git push --quiet origin HEAD:refs/heads/master
  git push --quiet origin HEAD:refs/heads/main
)

cd "$ROOT_DIR"

if [[ ! -f packages/ui/dist/index.html ]]; then
  echo "repro: building @invoker/ui..." >&2
  pnpm --filter @invoker/ui build >&2
fi
if [[ ! -f packages/surfaces/dist/index.js ]]; then
  echo "repro: building @invoker/surfaces..." >&2
  pnpm --filter @invoker/surfaces build >&2
fi
if [[ ! -f packages/app/dist/main.js ]]; then
  echo "repro: building @invoker/app..." >&2
  pnpm --filter @invoker/app build >&2
fi

cat >"$DRIVER_TMP" <<'JS_DRIVER'
// Auto-generated by scripts/repro/repro-startup-snapshot-refresh-overhead.sh.
// Resides under packages/app/ so Node's ESM resolver finds @playwright/test.
import { _electron as electron } from '@playwright/test';
import { pathToFileURL } from 'node:url';
import * as fs from 'node:fs/promises';
import { writeFileSync } from 'node:fs';
import * as path from 'node:path';

function arg(name, fallback) {
  const idx = process.argv.indexOf(`--${name}`);
  if (idx === -1 || idx === process.argv.length - 1) return fallback;
  return process.argv[idx + 1];
}

const TMP_DIR = arg('tmpdir');
const DB_DIR = arg('db');
const CONFIG_PATH = arg('config');
const BARE_REPO = arg('bare-repo');
const OUT_PATH = arg('out');
const WORKFLOW_COUNT = Number(arg('workflows', '6'));
const TASKS_PER_WORKFLOW = Number(arg('tasks', '4'));
const MAIN_JS = path.resolve(process.cwd(), 'dist', 'main.js');

if (!TMP_DIR || !DB_DIR || !CONFIG_PATH || !BARE_REPO || !OUT_PATH) {
  console.error('driver: missing required --tmpdir/--db/--config/--bare-repo/--out');
  process.exit(2);
}

function launchArgs() {
  return [
    ...(process.platform === 'linux'
      ? ['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--disable-gpu-compositing', '--disable-gpu-sandbox', '--disable-software-rasterizer']
      : []),
    MAIN_JS,
  ];
}

function launchEnv(extra) {
  return {
    ...process.env,
    NODE_ENV: 'test',
    TZ: 'UTC',
    INVOKER_DB_DIR: DB_DIR,
    INVOKER_ALLOW_DELETE_ALL: '1',
    INVOKER_E2E_ENABLE_COMPOSITOR: '1',
    INVOKER_REPO_CONFIG_PATH: CONFIG_PATH,
    ...(extra ?? {}),
  };
}

function buildPlan(index) {
  const tasks = [];
  for (let t = 0; t < TASKS_PER_WORKFLOW; t += 1) {
    tasks.push({
      id: `task-${index}-${t}`,
      description: `Task ${index}-${t}`,
      command: `echo task-${index}-${t}`,
      dependencies: t === 0 ? [] : [`task-${index}-${t - 1}`],
    });
  }
  return {
    name: `Startup Snapshot Repro ${index}`,
    repoUrl: pathToFileURL(BARE_REPO).href,
    onFinish: 'none',
    tasks,
  };
}

function planToYaml(plan) {
  const lines = [
    `name: ${JSON.stringify(plan.name)}`,
    `repoUrl: ${JSON.stringify(plan.repoUrl)}`,
    `onFinish: ${plan.onFinish}`,
    'tasks:',
  ];
  for (const task of plan.tasks) {
    lines.push(`  - id: ${JSON.stringify(task.id)}`);
    lines.push(`    description: ${JSON.stringify(task.description)}`);
    lines.push(`    command: ${JSON.stringify(task.command)}`);
    if (task.dependencies && task.dependencies.length > 0) {
      lines.push('    dependencies:');
      for (const dep of task.dependencies) {
        lines.push(`      - ${JSON.stringify(dep)}`);
      }
    }
  }
  return lines.join('\n') + '\n';
}

async function waitForInvoker(page) {
  await page.waitForLoadState('domcontentloaded');
  await page.waitForFunction(() => typeof window.invoker !== 'undefined', null, { timeout: 15000 });
}

async function seedWorkflows() {
  const app = await electron.launch({ args: launchArgs(), env: launchEnv() });
  try {
    const page = await app.firstWindow({ timeout: 15000 });
    await waitForInvoker(page);
    for (let idx = 0; idx < WORKFLOW_COUNT; idx += 1) {
      const yaml = planToYaml(buildPlan(idx));
      await page.evaluate((planText) => window.invoker.loadPlan(planText), yaml);
    }
    await page.waitForFunction(
      (expectedTaskCount) =>
        window.invoker.getTasks(true).then((result) => {
          const tasks = Array.isArray(result) ? result : result.tasks;
          const workflows = Array.isArray(result) ? [] : (result.workflows ?? []);
          return tasks.length >= expectedTaskCount && workflows.length > 0;
        }),
      WORKFLOW_COUNT * TASKS_PER_WORKFLOW,
      { timeout: 30000 },
    );
  } finally {
    await app.close();
  }
}

async function measureStartupSnapshot() {
  const app = await electron.launch({
    args: launchArgs(),
    env: launchEnv({ INVOKER_TEST_RESUME_PENDING_DELAY_MS: '15000' }),
  });
  try {
    const page = await app.firstWindow({ timeout: 20000 });
    await waitForInvoker(page);

    await page.waitForFunction(
      () => !!document.querySelector('[data-testid^="workflow-node-"]'),
      null,
      { timeout: 20000 },
    );

    const deadline = Date.now() + 15000;
    let logs = [];
    while (Date.now() < deadline) {
      logs = await page.evaluate(() => window.invoker.getActivityLogs(0, 1000));
      const haveBootstrap = logs.some((entry) => {
        if (entry.source !== 'ui-perf') return false;
        try {
          return JSON.parse(entry.message).metric === 'preload_bootstrap_sync';
        } catch { return false; }
      });
      const haveReplace = logs.some((entry) => {
        if (entry.source !== 'ui-perf') return false;
        try {
          return JSON.parse(entry.message).metric === 'useTasks_snapshot_replace';
        } catch { return false; }
      });
      if (haveBootstrap && haveReplace) break;
      await page.waitForTimeout(200);
    }

    return logs;
  } finally {
    await app.close();
  }
}

function parsePayload(message) {
  try { return JSON.parse(message); } catch { return null; }
}

async function main() {
  await seedWorkflows();
  const logs = await measureStartupSnapshot();

  const perfEntries = logs
    .filter((entry) => entry.source === 'ui-perf')
    .map((entry) => ({ id: entry.id, payload: parsePayload(entry.message) }))
    .filter((entry) => entry.payload !== null);

  const findByMetric = (metric) => perfEntries.find((entry) => entry.payload.metric === metric);
  const findAll = (metric) => perfEntries.filter((entry) => entry.payload.metric === metric);

  const bootstrap = findByMetric('preload_bootstrap_sync');
  const bootstrapStateEntry = findByMetric('startup_bootstrap_state');
  const snapshotReplaces = findAll('useTasks_snapshot_replace');
  const workflowGraphVisible = findByMetric('startup_workflow_graph_visible');
  const taskGraphVisible = findByMetric('startup_graph_visible');

  let redundantSnapshot = null;
  if (bootstrap) {
    redundantSnapshot = snapshotReplaces.find(
      (entry) => entry.id > bootstrap.id && entry.payload.forceRefresh === false,
    ) ?? null;
  }
  const firstSnapshotReplace = snapshotReplaces[0] ?? null;
  const measured = redundantSnapshot ?? firstSnapshotReplace;

  const result = {
    bootstrap: bootstrap
      ? {
          taskCount: bootstrap.payload.taskCount,
          workflowCount: bootstrap.payload.workflowCount,
          jsonSizeBytes: bootstrap.payload.jsonSizeBytes,
          durationMs: bootstrap.payload.durationMs,
          processElapsedMs: bootstrap.payload.processElapsedMs,
        }
      : null,
    bootstrapStateApplied: bootstrapStateEntry
      ? {
          taskCount: bootstrapStateEntry.payload.taskCount,
          workflowCount: bootstrapStateEntry.payload.workflowCount,
          elapsedMs: bootstrapStateEntry.payload.elapsedMs,
        }
      : null,
    snapshotReplace: measured
      ? {
          taskCount: measured.payload.taskCount,
          workflowCount: measured.payload.workflowCount,
          forceRefresh: measured.payload.forceRefresh,
          requestDurationMs: measured.payload.requestDurationMs,
          replaceDurationMs: measured.payload.replaceDurationMs,
          jsonSizeBytes: measured.payload.jsonSizeBytes,
          activityLogId: measured.id,
        }
      : null,
    snapshotReplaceCount: snapshotReplaces.length,
    redundantNonForcedAfterBootstrap: !!redundantSnapshot,
    workflowGraphVisible: workflowGraphVisible
      ? {
          nodeCount: workflowGraphVisible.payload.nodeCount,
          edgeCount: workflowGraphVisible.payload.edgeCount,
          elapsedMs: workflowGraphVisible.payload.elapsedMs,
          processElapsedMs: workflowGraphVisible.payload.processElapsedMs,
        }
      : null,
    taskGraphVisible: taskGraphVisible
      ? {
          nodeCount: taskGraphVisible.payload.nodeCount,
          elapsedMs: taskGraphVisible.payload.elapsedMs,
          processElapsedMs: taskGraphVisible.payload.processElapsedMs,
        }
      : null,
    expectedTaskCount: WORKFLOW_COUNT * TASKS_PER_WORKFLOW,
    expectedWorkflowCount: WORKFLOW_COUNT,
  };

  writeFileSync(OUT_PATH, JSON.stringify(result, null, 2));
}

main().catch((err) => {
  console.error('driver error:', err?.stack ?? err);
  process.exit(1);
});
JS_DRIVER

echo "repro: launching isolated startup fixture (workflows=$WORKFLOW_COUNT tasks/workflow=$TASKS_PER_WORKFLOW)..." >&2

PLAYWRIGHT_RUNNER=(node "$DRIVER_TMP"
  --tmpdir "$TMP_DIR"
  --db "$DB_DIR"
  --config "$CONFIG_PATH"
  --bare-repo "$BARE_REPO"
  --out "$OUT_JSON"
  --workflows "$WORKFLOW_COUNT"
  --tasks "$TASKS_PER_WORKFLOW"
)

(
  cd "$ROOT_DIR/packages/app"
  if command -v xvfb-run >/dev/null 2>&1 && [[ -z "${DISPLAY:-}" ]]; then
    xvfb-run --auto-servernum "${PLAYWRIGHT_RUNNER[@]}"
  else
    "${PLAYWRIGHT_RUNNER[@]}"
  fi
)

if [[ ! -f "$OUT_JSON" ]]; then
  echo "repro: driver did not produce $OUT_JSON" >&2
  exit 1
fi

python3 - "$OUT_JSON" "$EXPECT_ISSUE" <<'PY'
import json, sys

with open(sys.argv[1], 'r', encoding='utf-8') as f:
    result = json.load(f)
expect_issue = int(sys.argv[2]) == 1

bootstrap = result.get('bootstrap') or {}
snap = result.get('snapshotReplace') or {}
wf_graph = result.get('workflowGraphVisible') or {}
task_graph = result.get('taskGraphVisible') or {}

print('repro-summary:')
print(f"  expected_task_count: {result.get('expectedTaskCount')}")
print(f"  expected_workflow_count: {result.get('expectedWorkflowCount')}")
print(f"  preload_bootstrap_sync.taskCount: {bootstrap.get('taskCount')}")
print(f"  preload_bootstrap_sync.workflowCount: {bootstrap.get('workflowCount')}")
print(f"  preload_bootstrap_sync.jsonSizeBytes: {bootstrap.get('jsonSizeBytes')}")
print(f"  preload_bootstrap_sync.durationMs: {bootstrap.get('durationMs')}")
print(f"  useTasks_snapshot_replace.count: {result.get('snapshotReplaceCount')}")
print(f"  useTasks_snapshot_replace.forceRefresh: {snap.get('forceRefresh')}")
print(f"  useTasks_snapshot_replace.requestDurationMs: {snap.get('requestDurationMs')}")
print(f"  useTasks_snapshot_replace.replaceDurationMs: {snap.get('replaceDurationMs')}")
print(f"  useTasks_snapshot_replace.jsonSizeBytes: {snap.get('jsonSizeBytes')}")
print(f"  startup_workflow_graph_visible.nodeCount: {wf_graph.get('nodeCount')}")
print(f"  startup_workflow_graph_visible.edgeCount: {wf_graph.get('edgeCount')}")
print(f"  startup_workflow_graph_visible.elapsedMs: {wf_graph.get('elapsedMs')}")
print(f"  startup_workflow_graph_visible.processElapsedMs: {wf_graph.get('processElapsedMs')}")
print(f"  startup_graph_visible.nodeCount: {task_graph.get('nodeCount')}")
print(f"  startup_graph_visible.elapsedMs: {task_graph.get('elapsedMs')}")
print(f"  redundant_non_forced_after_bootstrap: {result.get('redundantNonForcedAfterBootstrap')}")

redundant = bool(result.get('redundantNonForcedAfterBootstrap'))
if expect_issue:
    if not redundant:
        print('repro: FAIL -- expected current buggy baseline to fire a non-forced '
              'useTasks_snapshot_replace after preload_bootstrap_sync, but none was observed.',
              file=sys.stderr)
        sys.exit(1)
    print('startup-snapshot-refresh-overhead issue reproduced: '
          'non-forced useTasks_snapshot_replace observed after preload_bootstrap_sync.')
    sys.exit(0)

if redundant:
    print('repro: FAIL -- a non-forced useTasks_snapshot_replace was recorded after '
          'preload_bootstrap_sync; the redundant startup snapshot has not been eliminated.',
          file=sys.stderr)
    sys.exit(1)
print('startup-snapshot-refresh-overhead fixed: '
      'no redundant non-forced startup snapshot observed after preload_bootstrap_sync.')
PY
