#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

MODE=""
KEEP_TEMP=0
TIMEOUT_SECONDS="${REPRO_TIMEOUT_SECONDS:-120}"

usage() {
  cat <<'EOF'
Usage:
  bash scripts/repro/repro-recreate-workflow-misses-downstream.sh \
       (--expect-bug | --expect-fixed) [--keep-temp]

What it proves:
  Direct calls to workflow-core's Orchestrator.recreateWorkflow(upstreamWorkflowId)
  do NOT cascade into a downstream workflow that depends on the upstream via an
  external merge gate. Tasks in the downstream workflow stay in their previous
  completed/running state instead of being reset to pending.

  The cross-workflow cascade observed in app/UI paths only fires when callers
  drive recreateWorkflow through the applyInvalidation pipeline. Direct callers
  of orchestrator.recreateWorkflow miss this cascade today.

Modes:
  --expect-bug     Asserts the CURRENT (buggy) behavior: after direct
                   orchestrator.recreateWorkflow(upstreamWorkflowId), downstream
                   tasks remain in completed/running state. Exits 0 if the bug
                   is observed (i.e. the test asserting buggy state passes).

  --expect-fixed   Asserts the FUTURE (fixed) behavior: after direct
                   orchestrator.recreateWorkflow(upstreamWorkflowId), every
                   downstream task is reset to pending. Exits 0 only once the
                   underlying workflow-core primitive cascades through the
                   downstream workflow on its own.

Options:
  --keep-temp      Do not delete the temporary Vitest file or work directory
                   on exit. Useful while debugging assertion changes.
  -h, --help       Print this help and exit.

Acceptance:
  --expect-bug   must exit 0 on the current branch.
  --expect-fixed must exit 0 once direct recreateWorkflow cascades downstream.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --expect-bug)
      MODE="bug"
      shift
      ;;
    --expect-fixed)
      MODE="fixed"
      shift
      ;;
    --keep-temp)
      KEEP_TEMP=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "repro: unknown arg: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$MODE" ]]; then
  echo "repro: one of --expect-bug or --expect-fixed is required" >&2
  usage >&2
  exit 2
fi

die() {
  echo "repro: $*" >&2
  exit 2
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

require_cmd pnpm
require_cmd mktemp

TESTS_DIR="$ROOT_DIR/packages/workflow-core/src/__tests__"
[[ -d "$TESTS_DIR" ]] || die "expected workflow-core tests dir at $TESTS_DIR"
[[ -f "$TESTS_DIR/helpers/cross-workflow-cascade-helpers.ts" ]] \
  || die "expected cross-workflow-cascade-helpers.ts under $TESTS_DIR/helpers"

TMP_DIR="$(mktemp -d "${TMPDIR:-/tmp}/invoker-repro-direct-recreate.XXXXXX")"
TEST_FILE="$(mktemp "$TESTS_DIR/tmp-repro-direct-recreate-workflow-misses-downstream.XXXXXX.test.ts")"
VITEST_LOG="$TMP_DIR/vitest.log"

cleanup() {
  if [[ "$KEEP_TEMP" != "1" ]]; then
    rm -f "$TEST_FILE" 2>/dev/null || true
    rm -rf "$TMP_DIR" 2>/dev/null || true
  else
    echo "==> repro: --keep-temp set; preserved artifacts" >&2
    echo "    test_file : $TEST_FILE" >&2
    echo "    tmp_dir   : $TMP_DIR" >&2
  fi
}
trap cleanup EXIT

cat > "$TEST_FILE" <<'TEST_EOF'
// Auto-generated by scripts/repro/repro-recreate-workflow-misses-downstream.sh.
// Do not edit; do not commit. The script deletes this file on exit.
//
// Drives the cross-workflow cascade fixture (setupChain) and then calls
// orchestrator.recreateWorkflow(upstreamWorkflowId) DIRECTLY, bypassing
// applyInvalidation. The downstream workflow's tasks are inspected against
// either the current buggy expectation or the future fixed expectation,
// chosen by REPRO_MODE in the environment.

import { describe, expect, it } from 'vitest';
import {
  InMemoryPersistence,
  makeOrchestrator,
  setupChain,
} from './helpers/cross-workflow-cascade-helpers.js';

const MODE = (process.env.REPRO_MODE ?? '').trim();
if (MODE !== 'bug' && MODE !== 'fixed') {
  throw new Error(
    `repro test requires REPRO_MODE=bug|fixed; got '${MODE || '<unset>'}'`,
  );
}

describe('direct Orchestrator.recreateWorkflow misses downstream cascade', () => {
  it(`downstream workflow tasks reflect '${MODE}' expectation after direct recreateWorkflow`, () => {
    const persistence = new InMemoryPersistence();
    const orchestrator = makeOrchestrator(persistence);
    const ctx = setupChain(orchestrator);

    expect(orchestrator.getTask(ctx.downstreamRootId)!.status).toBe('completed');
    expect(orchestrator.getTask(ctx.downstreamMidId)!.status).toBe('completed');
    expect(orchestrator.getTask(ctx.downstreamLastId)!.status).toBe('running');
    expect(orchestrator.getTask(ctx.downstreamMergeId)!.status).toBe('pending');

    orchestrator.recreateWorkflow(ctx.upstreamWfId);

    // recreateWorkflow resets the upstream workflow and may auto-start its
    // ready tasks, so the upstream task itself can come back as 'running'
    // immediately. The bug claim is about the DOWNSTREAM workflow staying
    // untouched, so we focus the assertions on those tasks.
    const downstreamStatuses = {
      root: orchestrator.getTask(ctx.downstreamRootId)!.status,
      mid: orchestrator.getTask(ctx.downstreamMidId)!.status,
      last: orchestrator.getTask(ctx.downstreamLastId)!.status,
      merge: orchestrator.getTask(ctx.downstreamMergeId)!.status,
    };

    if (MODE === 'bug') {
      expect(
        downstreamStatuses,
        `expected downstream tasks to remain untouched after direct recreateWorkflow; got ${JSON.stringify(downstreamStatuses)}`,
      ).toEqual({
        root: 'completed',
        mid: 'completed',
        last: 'running',
        merge: 'pending',
      });
    } else {
      expect(
        downstreamStatuses,
        `expected all downstream tasks to be pending after direct recreateWorkflow; got ${JSON.stringify(downstreamStatuses)}`,
      ).toEqual({
        root: 'pending',
        mid: 'pending',
        last: 'pending',
        merge: 'pending',
      });
    }
  });
});
TEST_EOF

REL_TEST_FILE="${TEST_FILE#"$ROOT_DIR/"}"
PKG_REL_TEST_FILE="${TEST_FILE#"$ROOT_DIR/packages/workflow-core/"}"

echo "==> repro: mode=$MODE"
echo "test_file : $REL_TEST_FILE"
echo "vitest_log: $VITEST_LOG"
echo "keep_temp : $KEEP_TEMP"

set +e
REPRO_MODE="$MODE" \
  timeout "$TIMEOUT_SECONDS" \
  pnpm --filter @invoker/workflow-core exec vitest run "$PKG_REL_TEST_FILE" \
  >"$VITEST_LOG" 2>&1
VITEST_STATUS=$?
set -e

echo "vitest_status: $VITEST_STATUS"

if [[ "$VITEST_STATUS" -eq 0 ]]; then
  echo "==> repro: observed behavior matches --expect-$MODE"
  exit 0
fi

echo "==> repro: observed behavior did NOT match --expect-$MODE" >&2
echo "---- vitest output ----" >&2
cat "$VITEST_LOG" >&2 || true
echo "-----------------------" >&2
exit 1
