import { afterEach, describe, expect, it } from 'vitest';
import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { tmpdir } from 'node:os';
import { gunzipSync } from 'node:zlib';
import {
  createDeleteAllSnapshot,
  createHourlySnapshot,
  pruneHourlySnapshots,
  resolveInvokerHomeRoot,
} from '../delete-all-snapshot.js';

const tmpRoots: string[] = [];

function makeDbRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'invoker-db-snapshot-test-'));
  tmpRoots.push(root);
  return root;
}

/** Snapshots are gzipped on write; decode back to the original text for assertions. */
function readSnapshotText(snapshotPath: string): string {
  return gunzipSync(readFileSync(snapshotPath)).toString('utf-8');
}

afterEach(() => {
  for (const root of tmpRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
  delete process.env.INVOKER_DB_DIR;
  delete process.env.INVOKER_HOURLY_BACKUP_RETENTION;
});

describe('delete-all-snapshot (no-adapter fallback)', () => {
  it('snapshots the main .db only — never copies live -wal/-shm sidecars', async () => {
    const root = makeDbRoot();
    const dbPath = join(root, 'invoker.db');
    writeFileSync(dbPath, 'db-main');
    writeFileSync(`${dbPath}-wal`, 'db-wal');
    writeFileSync(`${dbPath}-shm`, 'db-shm');

    const snapshot = await createDeleteAllSnapshot(root);
    expect(snapshot).toContain(join(root, 'db-backups', 'invoker.db.before-delete-all-'));
    expect(snapshot).toMatch(/\.gz$/);
    expect(existsSync(snapshot as string)).toBe(true);
    expect(existsSync((snapshot as string).replace(/\.gz$/, ''))).toBe(false); // raw intermediate removed
    expect(readSnapshotText(snapshot as string)).toBe('db-main');
    expect(existsSync(`${snapshot}-wal`)).toBe(false);
    expect(existsSync(`${snapshot}-shm`)).toBe(false);
  });

  it('creates hourly snapshots with hourly-auto label (fallback path)', async () => {
    const root = makeDbRoot();
    const dbPath = join(root, 'invoker.db');
    writeFileSync(dbPath, 'db-main');
    writeFileSync(`${dbPath}-wal`, 'db-wal');
    writeFileSync(`${dbPath}-shm`, 'db-shm');

    const snapshot = await createHourlySnapshot(root);
    expect(snapshot).toContain(join(root, 'db-backups', 'invoker.db.hourly-auto-'));
    expect(snapshot).toMatch(/\.gz$/);
    expect(existsSync(snapshot as string)).toBe(true);
    expect(readSnapshotText(snapshot as string)).toBe('db-main');

    expect(existsSync(`${snapshot}-wal`)).toBe(false);
    expect(existsSync(`${snapshot}-shm`)).toBe(false);
  });

  it('returns null when DB does not exist', async () => {
    const root = makeDbRoot();
    await expect(createDeleteAllSnapshot(root)).resolves.toBeNull();
    await expect(createHourlySnapshot(root)).resolves.toBeNull();
  });

  it('resolveInvokerHomeRoot honors INVOKER_DB_DIR', () => {
    const root = makeDbRoot();
    process.env.INVOKER_DB_DIR = root;
    expect(resolveInvokerHomeRoot()).toBe(root);
  });

  it('can snapshot a copied db file as generated by restore workflows', async () => {
    const root = makeDbRoot();
    const source = join(root, 'source.db');
    const dbPath = join(root, 'invoker.db');
    writeFileSync(source, 'restored-db');
    copyFileSync(source, dbPath);
    mkdirSync(join(root, 'db-backups'), { recursive: true });

    const snapshot = await createDeleteAllSnapshot(root);
    expect(readSnapshotText(snapshot as string)).toBe('restored-db');
  });
});

describe('delete-all-snapshot (adapter-backed backup)', () => {
  it('routes through the injected backup callback when provided (WAL-safe path)', async () => {
    // When the caller supplies a backup callback (bound to
    // SQLiteAdapter.backupTo in production), the snapshot function delegates
    // to it and never touches the source .db directly. This is what preserves
    // WAL frames not yet checkpointed into the main DB — see the WAL-safety
    // regression file for the real-adapter proof.
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'unused-because-adapter-handles-it');

    const calls: string[] = [];
    const snapshot = await createDeleteAllSnapshot(root, async (dest) => {
      calls.push(dest);
      writeFileSync(dest, 'from-adapter-backup');
    });

    expect(calls).toEqual([snapshot?.replace(/\.gz$/, '')]); // backup callback writes the raw path pre-compression
    expect(readSnapshotText(snapshot as string)).toBe('from-adapter-backup');
    expect(existsSync(`${snapshot}-wal`)).toBe(false);
    expect(existsSync(`${snapshot}-shm`)).toBe(false);
  });

  it('propagates backup callback errors so callers see the failure', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');

    await expect(
      createDeleteAllSnapshot(root, async () => {
        throw new Error('backup failed: disk full');
      }),
    ).rejects.toThrow(/disk full/);
  });

  it('leaves no partial snapshot or journal behind when the backup fails partway', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');

    await expect(
      createHourlySnapshot(root, async (dest) => {
        writeFileSync(dest, 'partial-backup-pages');
        writeFileSync(`${dest}-journal`, 'rollback-journal');
        throw new Error('database or disk is full');
      }),
    ).rejects.toThrow(/disk is full/);

    expect(readdirSync(join(root, 'db-backups'))).toEqual([]);
  });

  it('leaves no raw snapshot behind when compression fails', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    let rawPath = '';

    await expect(
      createHourlySnapshot(root, async (dest) => {
        rawPath = dest;
        writeFileSync(dest, 'complete-backup');
        mkdirSync(`${dest}.gz`);
      }),
    ).rejects.toThrow();

    expect(existsSync(rawPath)).toBe(false);
  });
});

function seedHourly(backupDir: string, count: number, withSidecars = false): void {
  mkdirSync(backupDir, { recursive: true });
  for (let i = 0; i < count; i += 1) {
    const base = join(backupDir, `invoker.db.hourly-auto-20260101-${String(i).padStart(6, '0')}-000Z`);
    writeFileSync(base, `main-${i}`);
    if (withSidecars) {
      writeFileSync(`${base}-wal`, `wal-${i}`);
      writeFileSync(`${base}-shm`, `shm-${i}`);
    }
  }
}

function hourlyBaseNames(backupDir: string): string[] {
  return readdirSync(backupDir).filter(
    (n) => n.startsWith('invoker.db.hourly-auto-') && !n.endsWith('-wal') && !n.endsWith('-shm'),
  );
}

describe('hourly snapshot retention', () => {
  it('createHourlySnapshot prunes the oldest snapshots beyond the retention limit', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 5);

    const snapshot = await createHourlySnapshot(root, undefined, 3);

    expect(snapshot).not.toBeNull();
    expect(existsSync(snapshot as string)).toBe(true); // newest survives
    expect(hourlyBaseNames(backupDir)).toHaveLength(3);
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000000-000Z'))).toBe(false);
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000004-000Z'))).toBe(true);
  });

  it('pruneHourlySnapshots deletes any legacy -wal/-shm sidecars of pruned snapshots', () => {

    const root = makeDbRoot();
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 4, true);

    expect(pruneHourlySnapshots(backupDir, 1)).toBe(3);

    for (let i = 0; i < 3; i += 1) {
      const base = `invoker.db.hourly-auto-20260101-${String(i).padStart(6, '0')}-000Z`;
      expect(existsSync(join(backupDir, base))).toBe(false);
      expect(existsSync(join(backupDir, `${base}-wal`))).toBe(false);
      expect(existsSync(join(backupDir, `${base}-shm`))).toBe(false);
    }
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000003-000Z'))).toBe(true);
  });

  it('pruneHourlySnapshots never deletes non-hourly snapshots', () => {
    const root = makeDbRoot();
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 3);
    writeFileSync(join(backupDir, 'invoker.db.before-delete-all-20260101-000000-000Z'), 'keep');
    writeFileSync(join(backupDir, 'invoker.db.before-prod-recreate-20260101-000000'), 'keep');

    pruneHourlySnapshots(backupDir, 1);

    expect(existsSync(join(backupDir, 'invoker.db.before-delete-all-20260101-000000-000Z'))).toBe(true);
    expect(existsSync(join(backupDir, 'invoker.db.before-prod-recreate-20260101-000000'))).toBe(true);
  });

  it('pruneHourlySnapshots with retain <= 0 disables pruning', () => {
    const root = makeDbRoot();
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 3);

    expect(pruneHourlySnapshots(backupDir, 0)).toBe(0);
    expect(hourlyBaseNames(backupDir)).toHaveLength(3);
  });

  it('createHourlySnapshot honors INVOKER_HOURLY_BACKUP_RETENTION', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 4);
    process.env.INVOKER_HOURLY_BACKUP_RETENTION = '2';

    await createHourlySnapshot(root);

    expect(hourlyBaseNames(backupDir)).toHaveLength(2);
  });

  it('treats empty/blank INVOKER_HOURLY_BACKUP_RETENTION as unset, not as "disable pruning"', async () => {
    const seed = 60;
    const keptWith = async (value: string | undefined): Promise<number> => {
      const root = makeDbRoot();
      writeFileSync(join(root, 'invoker.db'), 'db-main');
      const backupDir = join(root, 'db-backups');
      seedHourly(backupDir, seed);
      if (value === undefined) delete process.env.INVOKER_HOURLY_BACKUP_RETENTION;
      else process.env.INVOKER_HOURLY_BACKUP_RETENTION = value;
      await createHourlySnapshot(root);
      return hourlyBaseNames(backupDir).length;
    };

    const unsetKept = await keptWith(undefined);
    expect(unsetKept).toBeLessThan(seed + 1); // sanity: default pruning engaged
    for (const blank of ['', '   ']) {
      expect(await keptWith(blank)).toBe(unsetKept);
    }
  });
});

describe('hourly snapshot compression', () => {
  it('gzips the snapshot and shrinks realistic, compressible SQLite-shaped content', async () => {
    const root = makeDbRoot();
    // Real SQLite DBs are dominated by repeated schema/text structure, not
    // random bytes -- a repeating string is a closer proxy than random data
    // for what gzip actually sees in production.
    const compressible = 'CREATE TABLE tasks (id TEXT, description TEXT); '.repeat(20_000);
    writeFileSync(join(root, 'invoker.db'), compressible);

    const snapshot = await createHourlySnapshot(root);
    const rawBytes = Buffer.byteLength(compressible, 'utf-8');
    const gzBytes = statSync(snapshot as string).size;

    expect(readSnapshotText(snapshot as string)).toBe(compressible);
    expect(gzBytes).toBeLessThan(rawBytes / 2); // repetitive text compresses well below half
  });

  it('prunes a mix of legacy uncompressed and new .gz snapshots by count, oldest first', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 3); // legacy uncompressed, oldest

    const snapshot = await createHourlySnapshot(root, undefined, 2); // new .gz snapshot, newest

    const remaining = hourlyBaseNames(backupDir);
    expect(remaining).toHaveLength(2);
    expect(remaining).toContain(join(backupDir, 'invoker.db.hourly-auto-20260101-000002-000Z').split('/').pop());
    expect(existsSync(snapshot as string)).toBe(true); // the new .gz snapshot survives
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000000-000Z'))).toBe(false);
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000001-000Z'))).toBe(false);
  });
});

describe('interrupted snapshot cleanup', () => {
  it('leaves a snapshot that is still being compressed alone when another snapshot starts', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const payload = randomBytes(64 * 1024 * 1024);
    let slowRawPath = '';
    const slow = createHourlySnapshot(root, async (destination) => {
      slowRawPath = destination;
      writeFileSync(destination, payload);
    });
    while (!slowRawPath || !existsSync(`${slowRawPath}.gz`)) {
      await new Promise((resolve) => setTimeout(resolve, 1));
    }

    const other = await createDeleteAllSnapshot(root);
    const slowResult = await slow;

    expect(slowResult).toBe(`${slowRawPath}.gz`);
    expect(existsSync(slowResult as string)).toBe(true);
    expect(gunzipSync(readFileSync(slowResult as string)).equals(payload)).toBe(true);
    expect(readSnapshotText(other as string)).toBe('db-main');
  });

  it('removes a raw snapshot and its partial .gz left by an earlier interrupted run', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    mkdirSync(backupDir, { recursive: true });
    const stale = join(backupDir, 'invoker.db.hourly-auto-20260101-000000-000Z');
    writeFileSync(stale, 'full-raw-copy');
    writeFileSync(`${stale}.gz`, 'truncated');

    const snapshot = await createHourlySnapshot(root);

    expect(existsSync(stale)).toBe(false);
    expect(existsSync(`${stale}.gz`)).toBe(false);
    expect(readSnapshotText(snapshot as string)).toBe('db-main');
  });

  it('removes an interrupted pair from another label before a delete-all snapshot', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    mkdirSync(backupDir, { recursive: true });
    const stale = join(backupDir, 'invoker.db.hourly-auto-20260101-000000-000Z');
    writeFileSync(stale, 'full-raw-copy');
    writeFileSync(`${stale}.gz`, 'truncated');

    const snapshot = await createDeleteAllSnapshot(root);

    expect(existsSync(stale)).toBe(false);
    expect(existsSync(`${stale}.gz`)).toBe(false);
    expect(readSnapshotText(snapshot as string)).toBe('db-main');
  });

  it('keeps finished .gz snapshots and uncompressed snapshots that have no .gz sibling', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    mkdirSync(backupDir, { recursive: true });
    const finished = join(backupDir, 'invoker.db.hourly-auto-20260101-000000-000Z.gz');
    const legacy = join(backupDir, 'invoker.db.before-prod-recreate-20260101-000000');
    writeFileSync(finished, 'finished');
    writeFileSync(legacy, 'legacy');

    const snapshot = await createDeleteAllSnapshot(root);

    expect(readFileSync(finished, 'utf-8')).toBe('finished');
    expect(readFileSync(legacy, 'utf-8')).toBe('legacy');
    expect(existsSync(snapshot as string)).toBe(true);
  });

  it('still writes the new snapshot when removing an interrupted file fails', async () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    const stale = join(backupDir, 'invoker.db.hourly-auto-20260101-000000-000Z');
    mkdirSync(join(stale, 'child'), { recursive: true });
    writeFileSync(`${stale}.gz`, 'truncated');

    const snapshot = await createHourlySnapshot(root);

    expect(readSnapshotText(snapshot as string)).toBe('db-main');
  });
});
