import { afterEach, describe, expect, it } from 'vitest';
import {
  copyFileSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  createDeleteAllSnapshot,
  createHourlySnapshot,
  pruneHourlySnapshots,
  resolveInvokerHomeRoot,
} from '../delete-all-snapshot.js';

const tmpRoots: string[] = [];

function makeDbRoot(): string {
  const root = mkdtempSync(join(tmpdir(), 'invoker-db-snapshot-test-'));
  tmpRoots.push(root);
  return root;
}

afterEach(() => {
  for (const root of tmpRoots.splice(0)) {
    rmSync(root, { recursive: true, force: true });
  }
  delete process.env.INVOKER_DB_DIR;
  delete process.env.INVOKER_HOURLY_BACKUP_RETENTION;
});

describe('delete-all-snapshot', () => {
  it('creates delete-all snapshot with sqlite sidecar files', () => {
    const root = makeDbRoot();
    const dbPath = join(root, 'invoker.db');
    writeFileSync(dbPath, 'db-main');
    writeFileSync(`${dbPath}-wal`, 'db-wal');
    writeFileSync(`${dbPath}-shm`, 'db-shm');

    const snapshot = createDeleteAllSnapshot(root);
    expect(snapshot).toContain(join(root, 'db-backups', 'invoker.db.before-delete-all-'));
    expect(existsSync(snapshot)).toBe(true);
    expect(existsSync(`${snapshot}-wal`)).toBe(true);
    expect(existsSync(`${snapshot}-shm`)).toBe(true);
    expect(readFileSync(snapshot, 'utf-8')).toBe('db-main');
    expect(readFileSync(`${snapshot}-wal`, 'utf-8')).toBe('db-wal');
    expect(readFileSync(`${snapshot}-shm`, 'utf-8')).toBe('db-shm');
  });

  it('creates hourly snapshots with hourly-auto label', () => {
    const root = makeDbRoot();
    const dbPath = join(root, 'invoker.db');
    writeFileSync(dbPath, 'db-main');

    const snapshot = createHourlySnapshot(root);
    expect(snapshot).toContain(join(root, 'db-backups', 'invoker.db.hourly-auto-'));
    expect(existsSync(snapshot)).toBe(true);
    expect(readFileSync(snapshot, 'utf-8')).toBe('db-main');
  });

  it('returns null when DB does not exist', () => {
    const root = makeDbRoot();
    expect(createDeleteAllSnapshot(root)).toBeNull();
    expect(createHourlySnapshot(root)).toBeNull();
  });

  it('resolveInvokerHomeRoot honors INVOKER_DB_DIR', () => {
    const root = makeDbRoot();
    process.env.INVOKER_DB_DIR = root;
    expect(resolveInvokerHomeRoot()).toBe(root);
  });

  it('can snapshot a copied db file as generated by restore workflows', () => {
    const root = makeDbRoot();
    const source = join(root, 'source.db');
    const dbPath = join(root, 'invoker.db');
    writeFileSync(source, 'restored-db');
    copyFileSync(source, dbPath);
    mkdirSync(join(root, 'db-backups'), { recursive: true });

    const snapshot = createDeleteAllSnapshot(root);
    expect(readFileSync(snapshot, 'utf-8')).toBe('restored-db');
  });
});

function seedHourly(backupDir: string, count: number, withSidecars = false): void {
  mkdirSync(backupDir, { recursive: true });
  for (let i = 0; i < count; i += 1) {
    const base = join(backupDir, `invoker.db.hourly-auto-20260101-${String(i).padStart(6, '0')}-000Z`);
    writeFileSync(base, `main-${i}`);
    if (withSidecars) {
      writeFileSync(`${base}-wal`, `wal-${i}`);
      writeFileSync(`${base}-shm`, `shm-${i}`);
    }
  }
}

function hourlyBaseNames(backupDir: string): string[] {
  return readdirSync(backupDir).filter(
    (n) => n.startsWith('invoker.db.hourly-auto-') && !n.endsWith('-wal') && !n.endsWith('-shm'),
  );
}

describe('hourly snapshot retention', () => {
  it('createHourlySnapshot prunes the oldest snapshots beyond the retention limit', () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 5);

    const snapshot = createHourlySnapshot(root, 3);

    expect(snapshot).not.toBeNull();
    expect(existsSync(snapshot as string)).toBe(true); // newest survives
    expect(hourlyBaseNames(backupDir)).toHaveLength(3);
    // the three oldest seeded snapshots were removed
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000000-000Z'))).toBe(false);
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000004-000Z'))).toBe(true);
  });

  it('pruneHourlySnapshots deletes the -wal/-shm sidecars of pruned snapshots', () => {
    const root = makeDbRoot();
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 4, true);

    expect(pruneHourlySnapshots(backupDir, 1)).toBe(3);

    for (let i = 0; i < 3; i += 1) {
      const base = `invoker.db.hourly-auto-20260101-${String(i).padStart(6, '0')}-000Z`;
      expect(existsSync(join(backupDir, base))).toBe(false);
      expect(existsSync(join(backupDir, `${base}-wal`))).toBe(false);
      expect(existsSync(join(backupDir, `${base}-shm`))).toBe(false);
    }
    expect(existsSync(join(backupDir, 'invoker.db.hourly-auto-20260101-000003-000Z'))).toBe(true);
  });

  it('pruneHourlySnapshots never deletes non-hourly snapshots', () => {
    const root = makeDbRoot();
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 3);
    writeFileSync(join(backupDir, 'invoker.db.before-delete-all-20260101-000000-000Z'), 'keep');
    writeFileSync(join(backupDir, 'invoker.db.before-prod-recreate-20260101-000000'), 'keep');

    pruneHourlySnapshots(backupDir, 1);

    expect(existsSync(join(backupDir, 'invoker.db.before-delete-all-20260101-000000-000Z'))).toBe(true);
    expect(existsSync(join(backupDir, 'invoker.db.before-prod-recreate-20260101-000000'))).toBe(true);
  });

  it('pruneHourlySnapshots with retain <= 0 disables pruning', () => {
    const root = makeDbRoot();
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 3);

    expect(pruneHourlySnapshots(backupDir, 0)).toBe(0);
    expect(hourlyBaseNames(backupDir)).toHaveLength(3);
  });

  it('createHourlySnapshot honors INVOKER_HOURLY_BACKUP_RETENTION', () => {
    const root = makeDbRoot();
    writeFileSync(join(root, 'invoker.db'), 'db-main');
    const backupDir = join(root, 'db-backups');
    seedHourly(backupDir, 4);
    process.env.INVOKER_HOURLY_BACKUP_RETENTION = '2';

    createHourlySnapshot(root);

    expect(hourlyBaseNames(backupDir)).toHaveLength(2);
  });

  it('treats empty/blank INVOKER_HOURLY_BACKUP_RETENTION as unset, not as "disable pruning"', () => {
    // Regression: Number('') === 0 slipped through Number.isFinite && >= 0 and
    // disabled pruning, silently reintroducing unbounded growth. Empty/blank must
    // behave exactly like an unset variable. Seed above the default so pruning must
    // engage — the assertion compares blank vs unset rather than a hard-coded count.
    const seed = 60;
    const keptWith = (value: string | undefined): number => {
      const root = makeDbRoot();
      writeFileSync(join(root, 'invoker.db'), 'db-main');
      const backupDir = join(root, 'db-backups');
      seedHourly(backupDir, seed);
      if (value === undefined) delete process.env.INVOKER_HOURLY_BACKUP_RETENTION;
      else process.env.INVOKER_HOURLY_BACKUP_RETENTION = value;
      createHourlySnapshot(root);
      return hourlyBaseNames(backupDir).length;
    };

    const unsetKept = keptWith(undefined);
    expect(unsetKept).toBeLessThan(seed + 1); // sanity: default pruning engaged
    for (const blank of ['', '   ']) {
      expect(keptWith(blank)).toBe(unsetKept); // blank == unset, NOT disabled (would keep seed + 1)
    }
  });
});
